### ISSUE TITLE
Problem: SaveClient does not save session to local file

### ISSUE THREAD

**Issue by damoncro** [cronos-labs/play-unreal-plugin#169]
Use [SaveStringToFile](https://docs.unrealengine.com/4.27/en-US/API/Runtime/Core/Misc/FFileHelper/SaveStringToFile/index.html)

**Comment by leejw51crypto** [comment]
how about?
SaveClientToString
RestoreClientFromString

**Comment by damoncro** [comment]
> how about? SaveClientToString RestoreClientFromString

No these two functions but `SaveClient` and `RestoreClient`. 

As the title says, `SaveClient` does not save session to local file, this function does not have capability to save the session info into file.
