### ISSUE TITLE
Problem: BroadcastEthTxAsync is not under DefiWalletCoreActor

### ISSUE THREAD

**Issue by damoncro** [cronos-labs/play-unreal-plugin#170]
Move `BroadcastEthTxAsync` into member of `DefiWalletCoreActor`, so that the `rpc` configuration could be shared.

**Comment by leejw51crypto** [comment]
BroadcastEthTxAsync is stateless api, which doesn't use DefiWaletCoreActors' wallet variable.

**Comment by damoncro** [comment]
As @ricky321q mentioned, rpc setting is a shared parameter, it could be assigned to DefiWalletCoreActor for better user experience. Otherwise, user has to save rpc to a separate variable and retrieve it every time when he/she call BroadcastEthTxAsync.

**Comment by ricky321q** [comment]
Yeah, I think it'll bring more convenient to the user, and it's more easier.
Btw so for what user need to search BroadcastEthTxAsync like DefiWalletCoreActor in blueprint class?

**Comment by leejw51crypto** [comment]
ok
