### ISSUE TITLE
Problem: Naming of InitializeWallet and InitializeNewDevelopmentOnlyWallet are confusing

### ISSUE THREAD

**Issue by damoncro** [cronos-labs/play-unreal-plugin#171]

**Comment by ricky321q** [comment]
I suggest that we should rephrase wallet function naming.

For now we have

InitializeWallet should be RestoreWallet
InitializeNewDevelopmentOnlyWallet be InitializeNewWallet
GetBackupMnemonicPhrase Remain
DevelopmentOnlyGenerateMnemonics be GenerateMnemonics
GetEthAddress Remain
GetEthBalance Remain
SignEthAmount Remain
SendEthAmount or SendEthAmountAsync be SendEthAmount Should not have or at naming we just let devs know it could finish async but better not at naming
SignLogin Remain
VerifyLogin Remain
 

@damoncro @leejw51crypto WDYT
