### ISSUE TITLE
Problem: no secure secret storage option

### ISSUE THREAD

**Issue by tomtau** [cronos-labs/play-unreal-plugin#217]
see if this API can be used on macOS / iOS: https://developer.apple.com/documentation/security/keychain_services?language=objc
this on Android: https://developer.android.com/reference/android/security/KeyChain
or this on Windows: https://learn.microsoft.com/en-us/uwp/api/Windows.Security.Credentials?redirectedfrom=MSDN&view=winrt-22621

**Comment by tomtau** [comment]
@leejw51crypto @damoncro perhaps a good start for desktop platforms (this thin library supports Windows, Linux and macOS): https://github.com/hrantzsch/keychain

**Comment by tomtau** [comment]
or if it's done in the C++ SDK, perhaps it can add bindings that use this crate: https://crates.io/crates/keytar ?

**Comment by tomtau** [comment]
@damoncro @leejw51crypto https://crates.io/crates/keyring

**Comment by leejw51crypto** [comment]
ok, i'll start working on this issue

**Comment by leejw51crypto** [comment]
i'll check above crates first

**Comment by leejw51crypto** [comment]
started
using https://crates.io/crates/keyring
