### ISSUE TITLE
Problem: not supporting of verse in uefn

### ISSUE THREAD

**Issue by leejw51crypto** [cronos-labs/play-unreal-plugin#299]
add support for `verse` in unreal editor for fortnite
- wallet connect 2.0
- basic wallet 
- basic transfer

**Comment by tomtau** [comment]
Can UEFN support general UE plugins?

**Comment by leejw51crypto** [comment]
nope, only verse

**Comment by leejw51crypto** [comment]
yes, close for security issue, 

when there is ffi for verse, we can reopen
