### ISSUE TITLE
Problem: error in destroyCoreClient

### ISSUE THREAD

**Issue by leejw51crypto** [cronos-labs/play-unreal-plugin#346]
remove AsyncTask, free memory directly

**Comment by Tam4tik** [comment]
Is this related to UE crashing after using the wallet core features? 

![2024-01-24 17_19_31-Mousemaze Crash Reporter](https://github.com/cronos-labs/play-unreal-plugin/assets/92913181/ab0d0b0c-6f9d-4aaa-acfc-300b2b35a1f9)

**Comment by leejw51crypto** [comment]
yes

**Comment by leejw51crypto** [comment]
done
