### ISSUE TITLE
Problem: Missing windows release CI

### ISSUE THREAD

**Issue by damoncro** [cronos-labs/play-unreal-plugin#90]
For more native feeling, we could use batch, powershell, ninja or cmake for building and packing (bundled in visual studio C++), instead of `make` which needs to be run under cygwin or msys2, and they may not be installed.

**Comment by leejw51crypto** [comment]
currently, packaging uses no compilation.
using  linux.

i'll check other way in windows

**Comment by damoncro** [comment]
Pack under windows or mac instead of windows.

**Comment by leejw51crypto** [comment]
ok

**Comment by damoncro** [comment]
This issue is not needed anymore, since it was already implemented on play-unreal-demo CI.
