### ISSUE TITLE
Problem: release flow runs on pull requests

### ISSUE THREAD

**Issue by tomtau** [cronos-labs/play-unreal-plugin#96]
https://github.com/cronos-labs/play-unreal-plugin/blob/main/.github/workflows/release.yml#L11
currently, the flow doesn't do anything besides building C++ SDK and packing up the plugin, but it doesn't try to build the plugin... so there isn't much point of running it on pull requests.

**Comment by damoncro** [comment]
Maybe we could build the plugin in ci. Let me check.

**Comment by damoncro** [comment]
Maybe we need https://unrealcontainers.com/docs/use-cases/continuous-integration

**Comment by damoncro** [comment]
https://github.com/cronos-labs/play-unreal-plugin/issues/38

**Comment by leejw51crypto** [comment]
yes, we can provide compiled plugin by using ue4 docker
